[project]
name = "PyOLXGUI"
version = "0.1.0"
description = "PyOLXGUI is a simple Dominate based Python library for creating Olex2 GUI files"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "dominate>=2.9.1",
    "dotenv>=0.9.9",
    "icecream>=2.1.5",
    "jupyter>=1.1.1",
    "pygments>=2.19.1",
    "pytest>=8.3.5",
    "python-dotenv>=1.1.0",
]

[tool.uv.workspace]
members = ["olexpy"]
