[project]
name = "PyOLXGUI"
version = "0.1.0"
description = "PyOLXGUI is a simple Dominate based Python library for creating Olex2 GUI files"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "dominate>=2.9.1",
    "dotenv>=0.9.9",
    "jupyter>=1.1.1",
    "jupyterlab>=4.4.3",
    "pygments>=2.19.1",
]
